# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: mybluebuild # <-- MUST be lowercase to satisfy OCI registry standards
description: Custom gaming OS image for the Steam Deck with RetroDeck, Ryujinx, Kodi, Stremio, and autostarting Syncthing, Tailscale, & Decky.

base-image: ghcr.io/ublue-os/bazzite-deck
image-version: stable 

modules:
  - type: files
    files:
      - source: system
        destination: / 

  - type: rpm-ostree
    install:
      - micro
      - syncthing

  - type: default-flatpaks
    configurations:
      - notify: true 
        scope: system
        install: 
          - org.mozilla.firefox
          - net.retrodeck.retrodeck 
          - io.github.ryubing.Ryujinx 
          - tv.kodi.Kodi
          - com.stremio.Stremio
      - scope: user 

  - type: systemd
    system:
      enabled:
        - tailscaled.service   # Core secure virtual mesh engine daemon
    user:
      enabled:
        - syncthing.service    # User-space home directory mirror process